apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mariemchaabani/monitoring-backend:44
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: monitoring-secret
        volumeMounts:
        - name: backups
          mountPath: /app/backups
      volumes:
      - name: backups
        hostPath:
          path: /home/debian/DevOps-Monitoring-App/backups
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: monitoring
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
  type: NodePort