apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secret
  namespace: monitoring
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://mariem:Mariem12345@cluster0.begfnur.mongodb.net/monitoring?retryWrites=true&w=majority"
  EMAIL_USER: "mariemchaabani39@gmail.com"
  EMAIL_PASS: "zivenoqqcfwcefkx"
  PORT: "3000"
