apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secret
  namespace: monitoring
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://mariem:Mariem12345@cluster0.begfnur.mongodb.net/monitoring?retryWrites=true&w=majority"
  EMAIL_USER: "mariemchaabani39@gmail.com"
  EMAIL_PASS: "zivenoqqcfwcefkx"
  PORT: "3000"
  JWT_SECRET: "049996b92a2f77e822e24714c24db22ea9b357b99512feb8d0e7399b370d0123"
  ADMIN_EMAIL: "mariemchaabani39@gmail.com"
  ADMIN_PASSWORD: "nomadis@NOMADIS#123"
